# Generated by Django 2.2 on 2019-04-30 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='博客分类')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标签')),
            ],
            options={
                'verbose_name': '内容标签',
                'verbose_name_plural': '内容标签',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='条目标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='条目添加日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='条目修改时间')),
                ('abstract', models.TextField(blank=True, max_length=256, null=True, verbose_name='内容摘要')),
                ('body', models.TextField(verbose_name='条目正文')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog-images', verbose_name='条目配图')),
                ('visited', models.PositiveIntegerField(default=0, verbose_name='条目访问量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='条目作者')),
                ('category', models.ManyToManyField(to='blog.Category', verbose_name='条目类别')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='条目标签')),
            ],
            options={
                'verbose_name': '条目',
                'verbose_name_plural': '条目',
                'ordering': ['-created_time'],
            },
        ),
    ]
